Remove docs and update lint workflow

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -26,9 +26,15 @@ jobs:
       - name: make fix
         run: |
           make fix
-      - name: Commit changes
-        uses: EndBug/add-and-commit@v9
+      - name: Check for changes
+        id: check-changed-files
+        uses: tj-actions/verify-changed-files@v11.1
         with:
-          message: 'Fix linting'
-          author_name: GitHub Actions
-          author_email: 41898282+github-actions[bot]@users.noreply.github.com
+          files : |
+            *
+      - name: Fail if code needs linting
+        if: steps.check-changed-files.outputs.files_changed == 'true'
+        run: |
+          echo "Changed files: ${{ steps.check-changed-files.outputs.changed_files }}"
+          echo "Run make fix to attempt to fix linter errors."
+          exit 1
